### PR TITLE
fix:  java.io.IOException: The current offset on block-info isn't upd…

### PR DESCRIPTION
**Pull request by ckjavacoder**
java.io.IOException: The current offset on block-info isn't update correct, x!= -1

### CODE REVIEW

**Comment by rantianhua** [comment]
This cannot solve the problem. I have a pull request for this https://github.com/lingochamp/okdownload/pull/346.

**Comment by ckjavacoder** [comment]
我应用了#346 还是不能下载https://cdn.llscdn.com/yy/files/xs8qmxn8-lls-LLS-5.8-800-20171207-111607.apk  还是会到 Error
12-09 09:17:10.724 21083-21083/com.liulishuo.okdownload.sample E/SingleActivity: download error
    java.io.IOException: The current offset on block-info isn't update correct, 8436771 != 14664668 on 1
        at com.liulishuo.okdownload.core.file.MultiPointOutputStream.inspectComplete(MultiPointOutputStream.java:267)
        at com.liulishuo.okdownload.core.interceptor.BreakpointInterceptor.interceptFetch(BreakpointInterceptor.java:123)
        at com.liulishuo.okdownload.core.download.DownloadChain.processFetch(DownloadChain.java:220)
        at com.liulishuo.okdownload.core.interceptor.RetryInterceptor.interceptFetch(RetryInterceptor.java:57)


这个异常只会有多线程下载情况下出现 我这边的 connectionCount 

所以我这个改动应该和#346不一样

**Comment by ckjavacoder** [comment]
可能是我问题描述错了应该是  The current offset on block-info isn't update correct, 8436771 != 14664668 on 1

**Comment by rantianhua** [comment]
那你这个属于另外的问题，我会用你提供的链接尝试一下看看。

**Comment by fazhongxu** [comment]
我也遇到了  ，The current offset on block-info isn't update correct, 2490532 != 2605681 on 2

**Comment by mradzinski** [comment]
Why was this closed @rantianhua? This issue is still happening for everyone running Android 10: `The current offset on block-info isn't update correct, 932763 != 4998011 on 0`. Does #346 fixes it? If not then this PR needs to be reopened, tested and merged ASAP.

**Comment by saeed74** [comment]
`The current offset on block-info isn't update correct` also still Happening on android 11

**Pull request closed without merging**
